import LeftSide from "@/components/leftSide";
import ConfirmModal from "@/components/mocules/confirmModal";
import CustomizedSnackbars from "@/components/mocules/snackbars";
import RightSide from "@/components/rightSide";
import constants from "@/constants/index";
import useForceSignIn from "@/hooks/useForceSignIn";
import { signIn } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { ReactNode, useState } from "react";
import styles from "./styles.module.css";

export interface ContainerProps {
  children: ReactNode;
  page: string;
}

export default function Container({ children, page }: ContainerProps) {
  useForceSignIn();

  const [loginRequireVisible, setLoginRequireVisible] =
    useState<boolean>(false);

  const handleSignInConfirmClick = async () => {
    await signIn("google");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>{"Welcome !"}</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href={
            "https://res.cloudinary.com/dggrsi7ck/image/upload/v1671247771/app-logo_emyf9f.png"
          }
        />
      </Head>
      <main className={styles.main}>
        <LeftSide currentPage={page} />
        <div className={styles.contentContainer}>{children}</div>
        <RightSide />
      </main>
      <CustomizedSnackbars />
      <ConfirmModal
        trigger={undefined}
        title={constants.loginRequireTitle}
        description={constants.loginRequireBody}
        visible={loginRequireVisible}
        onConfirmClick={handleSignInConfirmClick}
        onCloseClick={() => setLoginRequireVisible(false)}
        loading={false}
      />
      <footer className={styles.footer}>
        <a
          href="https://service-social-media.herokuapp.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="https://res.cloudinary.com/dggrsi7ck/image/upload/v1671247771/app-logo_emyf9f.png"
              alt="Vercel Logo"
              width={50}
              height={50}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
