import {
  CardTitleText,
  HashTagText,
  SmallGreyText,
} from "@/components/atoms/appTexts";
import LeftSide from "@/components/leftSide";
import RightSide from "@/components/rightSide";
import { explores } from "@/dummyData/explore.json";
import appPages from "@/shared/appPages";
import { ArrowBackRounded } from "@mui/icons-material";
import { Avatar, Head, Image, Text } from "@nextui-org/react";
import React from "react";
import styles from "./styles.module.css";

export default function Explore(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Explore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LeftSide currentPage={appPages.home} />
        <div className={styles.contentContainer}>
          <div className={styles.exploreHeader}>
            <ArrowBackRounded />
            <Text>Explore</Text>
          </div>
          <ExploreList />
        </div>
        <RightSide />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const ExploreList = (props) => {
  return (
    <div className={styles.exploreList}>
      {explores.map((exploreItem) => (
        <ExploreItem key={exploreItem.id} {...exploreItem} />
      ))}
    </div>
  );
};

const ExploreItem = (props) => {
  const { id, topic, title, description, hashtag, tweetQuantity, mediaUrl } =
    props;

  return (
    <div className={styles.exploreItem}>
      <div className={styles.exploreItemDescription}>
        <SmallGreyText text={topic} />
        <CardTitleText text={title} />
        <SmallGreyText text={description} />
        <HashTagText text={hashtag} />
        <SmallGreyText text={tweetQuantity} />
      </div>
      <Avatar css={{ borderRadius: "2rem" }} size={50} src={mediaUrl} />
    </div>
  );
};
