import { AppPageLoading } from "@/components/atoms/AppLoading";
import NavigationBar, {
  homeActiveTabs,
} from "@/components/home/navigation_bar";
import EvaluationPost from "@/components/home/post";
import RecommendFollowableUsers from "@/components/home/recommendFollowableUsers";
import UserStatusInput from "@/components/home/userStatusInput";
import LeftSide from "@/components/leftSide";
import ConfirmModal from "@/components/mocules/confirmModal";
import CustomizedSnackbars from "@/components/mocules/snackbars";
import RightSide from "@/components/rightSide";
import useNewsFeed from "@/hooks/useNewsFeed";
import { useRefreshNewsFeed } from "@/hooks/useRefreshNewsFeed";
import appPages from "@/shared/appPages";
import { TrendingPostsRequestDto } from "apis/home/interfaces";
import postListAPI from "apis/home/postListAPI";
import { GetServerSideProps } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import { AuthState } from "redux/slices/auth/authSlice";
import { PostState } from "redux/slices/home/posts/postListSlice";
import { convertPostListDtoToPostListState } from "redux/slices/home/posts/postsConverter";
import { setTrendingPosts } from "redux/slices/trending/trendingSlice";
import { RootState, useAppDispatch } from "redux/store/store";
import styles from "./styles.module.css";

export default function Home({ posts: initialPosts }: HomeGetServerSideProps) {
  const dispatch = useAppDispatch();
  const router = useRouter();
  const { data: session } = useSession();
  const {
    session: authSession,
    syncDBStatus,
    sessionStatus,
  }: AuthState = useSelector((state: RootState) => state.auth);
  const { posts, loading: postsLoading } = useSelector(
    (state: RootState) => state.postList
  );
  useNewsFeed({ initialPosts });
  useRefreshNewsFeed();
  const [loginRequireVisible, setLoginRequireVisible] =
    useState<boolean>(false);

  useEffect(() => {
    if (initialPosts) {
      dispatch(setTrendingPosts(initialPosts));
    }
  }, [initialPosts]);

  useEffect(() => {
    if ((session as any)?.error === "RefreshAccessTokenError") {
      signIn(); // Force sign in to hopefully resolve error
    }
  }, [session]);

  const handlePageClick = () => {
    if (authSession == null) {
      setLoginRequireVisible(true);
    }
  };

  const handleSignInConfirmClick = async () => {
    await signIn("google");
  };

  return (
    <div className={styles.container} onClick={handlePageClick}>
      <Head>
        <title>{"Let's explore nice places !"}</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href={
            "https://res.cloudinary.com/dggrsi7ck/image/upload/v1671247771/app-logo_emyf9f.png"
          }
        />
      </Head>
      <main className={styles.main}>
        <LeftSide currentPage={appPages.home} />
        <div className={styles.contentContainer}>
          <NavigationBar tabs={homeActiveTabs} type="APP" />
          <UserStatusInput />
          <RecommendFollowableUsers />
          <div className={styles.listPost}>
            {sessionStatus == "unauthenticated" && initialPosts?.length > 0 ? (
              initialPosts.map((post: PostState) => (
                <EvaluationPost key={post.id} postState={post} />
              ))
            ) : postsLoading == "loading" || syncDBStatus == "pending" ? (
              <AppPageLoading />
            ) : (
              posts.map((post: PostState) => (
                <EvaluationPost key={post.id} postState={post} />
              ))
            )}
          </div>
        </div>
        <RightSide />
      </main>
      <CustomizedSnackbars />
      <ConfirmModal
        trigger={undefined}
        title={"Please login to use the application !"}
        description={
          "You need login by your google account, or register a new account to use full features of this application."
        }
        visible={loginRequireVisible}
        onConfirmClick={handleSignInConfirmClick}
        onCloseClick={() => setLoginRequireVisible(false)}
        loading={false}
      />
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export interface HomeGetServerSideProps {
  posts?: PostState[];
}

export const getServerSideProps: GetServerSideProps<
  HomeGetServerSideProps
> = async () => {
  const request: TrendingPostsRequestDto = {
    offset: 0,
    limit: 10,
    min_like_count: 3,
    min_comment_count: 5,
    min_share_count: 3,
  };

  const data = await postListAPI.getTrendingPosts(request);

  const posts = convertPostListDtoToPostListState({
    postListDto: data.evaluation_post,
  });

  return {
    props: {
      posts,
    },
  };
};
