import { AppPageLoading } from "@/components/atoms/AppLoading";
import NavigationBar, {
  homeActiveTabs,
} from "@/components/home/navigation_bar";
import EvaluationPost from "@/components/home/post";
import RecommendFollowableUsers from "@/components/home/recommendFollowableUsers";
import UserStatusInput from "@/components/home/userStatusInput";
import LeftSide from "@/components/leftSide";
import ConfirmModal from "@/components/mocules/confirmModal";
import CustomizedSnackbars from "@/components/mocules/snackbars";
import RightSide from "@/components/rightSide";
import constants from "@/constants/index";
import useForceSignIn from "@/hooks/useForceSignIn";
import appPages from "@/shared/appPages";
import { getHtmlCommentId } from "@/shared/utils/home";
import { SinglePostRequestDto } from "apis/home/interfaces";
import postListAPI from "apis/home/postListAPI";
import { GetServerSideProps, GetServerSidePropsContext } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import { AuthState } from "redux/slices/auth/authSlice";
import { fetchCommentsByPostID } from "redux/slices/home/comments/commentsSlice";
import { PostListState, PostState } from "redux/slices/home/posts/interfaces";
import { setPostsList } from "redux/slices/home/posts/postListSlice";
import { convertPostListDtoToPostListState } from "redux/slices/home/posts/postsConverter";
import { RootState, useAppDispatch } from "redux/store/store";
import styles from "./styles.module.css";

export default function EvaluationPostPage({
  posts: initialPosts,
  commentId,
  commentThreadId,
}: PostPageGetServerSideProps) {
  const dispatch = useAppDispatch();
  useForceSignIn();

  const { session: authSession }: AuthState = useSelector(
    (state: RootState) => state.auth
  );
  const { posts }: PostListState = useSelector(
    (state: RootState) => state.postList
  );

  const [loginRequireVisible, setLoginRequireVisible] =
    useState<boolean>(false);

  useEffect(() => {
    dispatch(setPostsList(initialPosts));
  }, [initialPosts]);

  // Scroll to specific comment if its id is specified in the route path
  useEffect(() => {
    if (posts.length > 0 && commentId && commentThreadId) {
      dispatch(fetchCommentsByPostID({ postId: posts[0].id })).then(() => {
        const commentElement = document.getElementById(
          // Not yet implement openning replies here, so just navigate to the parent comment.
          getHtmlCommentId(
            posts[0].id,
            commentThreadId > 0 ? commentThreadId : commentId
          )
        );

        commentElement &&
          window.scrollTo(commentElement.offsetLeft, commentElement.offsetTop);
      });
    }
  }, [posts, commentId, commentThreadId]);

  const handlePageClick = () => {
    if (authSession == null) {
      setLoginRequireVisible(true);
    }
  };

  const handleSignInConfirmClick = async () => {
    await signIn("google");
  };

  return (
    <div className={styles.container} onClick={handlePageClick}>
      <Head>
        <title>{"Let's explore nice places !"}</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href={
            "https://res.cloudinary.com/dggrsi7ck/image/upload/v1671247771/app-logo_emyf9f.png"
          }
        />
      </Head>
      <main className={styles.main}>
        <LeftSide currentPage={appPages.home} />
        <div className={styles.contentContainer}>
          <NavigationBar tabs={homeActiveTabs} type="APP" />
          <UserStatusInput />
          <RecommendFollowableUsers />
          <div className={styles.listPost}>
            {posts.length == 0 ? (
              <AppPageLoading />
            ) : (
              posts.map((post: PostState) => (
                <EvaluationPost key={post.id} postState={post} />
              ))
            )}
          </div>
        </div>
        <RightSide />
      </main>
      <CustomizedSnackbars />
      <ConfirmModal
        trigger={undefined}
        title={constants.loginRequireTitle}
        description={constants.loginRequireBody}
        visible={loginRequireVisible}
        onConfirmClick={handleSignInConfirmClick}
        onCloseClick={() => setLoginRequireVisible(false)}
        loading={false}
      />
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export interface PostPageGetServerSideProps {
  posts?: PostState[];
  commentId?: number;
  commentThreadId?: number;
}

export const getServerSideProps: GetServerSideProps<
  PostPageGetServerSideProps
> = async (context: GetServerSidePropsContext) => {
  const posts = await getPostsOfPostPageFromContext(context);

  return {
    props: {
      posts,
    },
  };
};

export const getPostsOfPostPageFromContext = async (
  context: GetServerSidePropsContext
) => {
  const id = context.params.id;
  const sessionUserId = context.params.sessionUserId;

  const request: SinglePostRequestDto = {
    post_id: parseParamToInt(id),
    user_id: parseParamToInt(sessionUserId),
  };

  const data = await postListAPI.getEvaluationPost(request);

  const posts = convertPostListDtoToPostListState({
    postListDto: data.evaluation_post,
    sessionUserId: parseParamToInt(sessionUserId),
  });

  return posts;
};

const parseParamToInt = (id: string | string[]) => {
  return typeof id == "string" ? parseInt(id) : parseInt(id[0]);
};
